/* ---------------- melodie language texts ---------------- */

var lang = {

// ---- Español - lang[es] ----
'es': {
	'langName': 'Español',
	'startup': {
		'welcome': 'Bienvenido a mélodie',
		'intro': 'Para configurar la aplicación debes indicar la ubicación dónde se almacenarán los archivos de audio y las carátulas de los discos',
		'audioPlaceholder': 'ruta de los archivos de audio',
		'coverPlaceholder': 'ruta que contiene las carátulas de los discos',
		'clearBtn': 'Borrar',
		'continueBtn': 'Continuar',
		'restoreOptionTxt': 'o<br />Importa una copia de seguridad de mélodie',
		'restoreBtn': 'Restaurar copia',
		'userManual': 'Manual de usuario',
	},
	'nav': {
		'home': 'home',
		'mysongs': 'mis canciones',
		'myplaylists': 'mis playlists',
		'noPlaylists': 'No hay playlists',
		'settings': 'configuración',
		'playingIcon': 'reproduciendo'
	},
	'homePage': {
		'homeTitle': 'Bienvenido a %%',
		'homeSubtitle': '¿Qué quieres escuchar hoy?',
		'showAllSongs': 'ver todas las canciones',
		'songs': 'Canciones',
		'totalPlays': 'Reproducciones',
		'artists': 'Artistas',
		'playlists': 'Playlists',
		'notPlayedSongs': 'Hace tiempo que no escuchas',
		'notPlayedEver': 'No se ha reproducido nunca',
		'notPlayedSince': {
			'minutes': ['Desde hace más de %% minuto','Desde hace más de %% minutos'],
			'hours': ['Desde hace mas de %% hora','Desde hace mas de %% horas'],
			'days': ['Desde hace mas de %% día','Desde hace mas de %% días'],
			'months': ['Desde hace mas de %% mes','Desde hace mas de %% meses'],
			'years': ['Desde hace mas de %% año','Desde hace mas de  %% años'],
		},
		'mostPlayedSongs': 'Canciones más escuchadas',
		'timesPlayed': 'veces',
		'showMore': 'ver más',
		'warnings': {
			'audioPath': 'Aviso: debe indicar la ruta de los archivos de audio en configuración',
			'coverPath': 'Aviso: debe indicar la ruta de las imágenes de los discos en configuración',
			'backupNever': 'Aviso: todavía no se realizado ninguna copia de seguridad',
			'backupTwoWeeks': 'Aviso: no se realiza copia de seguridad desde hace más de dos semanas',
			'backupMonth': 'Aviso: no se realiza copia de seguridad desde hace más de un mes',
		},
		'firstSteps': {
			'title': 'Primeros pasos',
			'songs': ['Añade todas tus canciones','encontrarás todas en la sección Mis Canciones'],
			'playlists': ['Crea listas de reproducción','clasifica tus canciones como quieras'],
			'backup': ['Guarda copias de seguridad','para evitar perder datos al borrar datos del navegador'],
		},
	},
	'mySongs': {
		'pageTitle': 'Lista de canciones',
		'songs': ['canción','canciones'],
		'minutes': ['minuto','minutos'],
		'hours': ['hora','horas'],
		'searchSongs': 'buscar canción',
		'songTitle': 'Título',
		'songArtist': 'Artista',
		'songAlbum': 'Álbum',
		'songGenre': 'Género',
		'songDuration': 'Duración',
		'songDateAdded': 'Fecha incorporación',
		'noSongs': 'No hay canciones',
	},
	'addSong': {
		'title': 'Añadir canción',
		'subtitle': 'Añade una canción a la lista de canciones',
		'titleBanner': 'Introduzca los datos de la nueva canción',
		'songTitle': {
			'desc': 'Título de la canción',
			'placeholder': 'escribe aquí el título',
		},
		'songArtist': {
			'desc': 'Nombre del artista',
			'placeholder': 'escribe aquí el nombre',
		},
		'songAlbum': {
			'desc': 'Nombre del álbum',
			'placeholder': 'escribe aquí el nombre',
		},
		'songGenre': {
			'desc': 'Género musical',
			'placeholder': 'escribe aquí el género',
		},
		'songPublished': {
			'desc': 'Lanzamiento',
			'placeholder': 'escribe aquí el año',
		},
		'songCover': {
			'desc': 'Carátula del disco',
			'placeholder': 'escribe la ruta de la carátula del disco',
		},
		'songAudio': {
			'desc': 'Archivo de audio',
			'placeholder': 'escribe la ruta del archivo de audio',
		},
		'requiredData': 'dato obligatorio',
		'select': 'Seleccionar',
	},
	'editSong': {
		'title': 'Editar canción',
		'subtitle': 'Edita la canción %% de %%',
		'titleBanner': 'Edite los cambios de la canción',
	},
	'deleteSong': {
		'title': 'Eliminar canción',
		'mainMessage': 'Está seguro de que desea eliminar la canción %% de forma permanente.',
		'relatedPlaylistsMsg': 'Se eliminará también de las playlists: %%.',
		'noRelatedPlaylistsMsg': 'La canción no se encuentra en ninguna playlist.',
		'acceptBtn': 'Eliminar',
		'discardBtn': 'Cancelar',
	},
	'newPlaylist': {
		'title': 'Nueva playlist',
		'mainMessage': 'Elije el nombre para la nueva playlist',
		'songAdded': 'Se añadirá la canción %% a la nueva playlist',
		'placeholder': 'escribe aquí el título',
		'acceptBtn': 'Crear',
		'discardBtn': 'Cancelar',
	},
	'renamePlaylist': {
		'title': 'Renombrar playlist',
		'mainMessage': 'Elije un nuevo nombre para la playlist %%',
		'placeholder': 'escribe aquí el nuevo nombre',
		'acceptBtn': 'Renombrar',
		'discardBtn': 'Cancelar',
	},
	'deletePlaylist': {
		'title': 'Eliminar playlist',
		'mainMessage': 'Está seguro de que desea eliminar la playlist %% de forma permanente.',
		'acceptBtn': 'Eliminar',
		'discardBtn': 'Cancelar',
	},
	'settings': {
		'title': 'Configuración',
		'lastUpdated': 'Actualizado por última vez el %%',
		'backup': {
			'title': 'Copia de seguridad',
			'backupText': 'Descarga una copia de seguridad de todos los datos de la aplicación',
			'backupBtn': 'Descargar copia',
			'lastBackup': 'última copia: %%',
			'noLastBackup': 'nunca se ha realizado una copia',
			'restoreText': 'Restaura los datos desde una copia de seguridad anterior. ¡Cuidado! se perderán todos los datos actuales',
			'restoreBtn': 'Seleccionar archivo',
			'restoreNoSelected': 'ningún archivo seleccionado',
			'restoreConfirmBtn': 'Restaurar',
		},
		'darkMode': {
			'title': 'Modo oscuro',
			'message': 'Activa el modo oscuro para evitar dañarte la vista',
			'enabled': 'Activado',
			'disabled': 'Desactivado',
		},
		'showPlaylists': {
			'title': 'Mostrar playlists',
			'message': 'Mostrar las playlists en el menú lateral por defecto',
			'enabled': 'Activado',
			'disabled': 'Desactivado',
		},
		'fileLocations': {
			'title': 'Ubicación archivos',
			'audioMessage': 'Indica la ruta en la que se almacenan los archivos de audio. Deberás almacenar en este directorio todas las canciones que añadas.',
			'audioPlaceholder': 'escribe la ruta que almacenará los archivos de audio',
			'coverMessage': 'Indica la ruta en la que se almacenan los archivos de las carátulas de los discos',
			'coverPlaceholder': 'escribe la ruta con los archivos de imágenes de los discos',
			'change': 'cambiar',
		},
		'avoidedSongs': {
			'title': 'Canciones evitadas',
			'message': 'Puedes evitar las canciones que se te hacen repetitivas durante 15 días. Podrás seguir reproduciéndolas haciendo clic sobre ellas, pero no figurarán en la cola hasta que el tiempo expire.<br /><br />Lista de canciones evitadas:',
			'songTitle': 'Título',
			'artist': 'Artista',
			'endDate': 'Fecha fin',
			'unavoid': 'Dejar de evitar',
			'unavoidBtn': 'Dejar de evitar canción',
			'noSongsAvoided': 'No hay canciones evitadas',
		},
		'language': {
			'title': 'Idioma de la página',
			'message': 'Los textos de la página se mostrarán en el idioma seleccionado',
		},
		'availableStorage': {
			'title': 'Almacenamiento disponible',
			'message': 'Información sobre el almacenamiento disponible en localstorage para que la aplicación pueda funcionar',
			'appUsage': 'Uso de %%: %%',
			'localstorageUsage': 'Uso de localstorage: %%',
		}
	},
	'context': {
		'editSong': 'editar',
		'deleteSong': 'eliminar',
		'avoidSong': 'evitar canción',
		'unavoidSong': 'dejar de evitar',
		'addToPlaylist': 'añadir a playlist ->',
		'addToNewPlaylist': 'Nueva playlist',
		'newPlaylist': 'Nueva playlist',
		'renamePlaylist': 'Renombrar',
		'deletePlaylist': 'Eliminar',
	},
	'errors': {
		'general': { // err #1000 (critical app errors)
			'changeLangErr1': {'code':'#1101','message':'The language selected is not available.'},
			'playSongErr1': {'code':'#1201','message':'No se ha podido reproducir la canción'},
			'startupErr1': {'code':'#1301','message':'Indica la ruta que contendrá los archivos de audio'},
			'startupErr2': {'code':'#1302','message':'Indica la ruta que contendrá las carátulas de los discos'},
			'startupErr3': {'code':'#1303','message':'debes escribir las rutas con los archivos de audio y las carátulas de los discos'},
		},
		'data': { // err #2000 (importdata, integrity of the data)
			'importErr1': {'code':'#2001','message':'El fichero no tiene el formato adecuado.'},
			'importErr2': {'code':'#2002','message':'El fichero no tiene el formato adecuado.'},
			'importErr3': {'code':'#2003','message':'El fichero no tiene el formato adecuado.'},
			'importErr4': {'code':'#2004','message':'Los datos son de una versión diferente de la aplicación, pueden ocurrir errores.'},
		},
		'songs': { // err #3000 (related to songs)
			'addErr1': 		{'code':'#3001','message':'Faltan datos obligatorios'},
			'addErr2': 		{'code':'#3002','message':'El formato de la imagen o el audio es erróneo'},
			'addErr3': 		{'code':'#3003','message':'El archivo de audio ya se ha utilizado en otra canción ya registrada'},
			'addErr4': 		{'code':'#3004','message':'Se ha producido un error al leer el archivo de audio introducido'},
			'addErr5': 		{'code':'#3005','message':'El audio introducido no se ha podido reproducir'},
			'editErr1': 	{'code':'#3101','message':'Faltan datos obligatorios'},
			'deleteErr1': 	{'code':'#3201','message':'Se ha producido un error al borrar la canción'},
		},
		'playlists': { // err #4000 (related to playlists)
			'addErr1': 		{'code':'#4001', 'message':'Debe introducir un nombre para la playlist'},
			'renameErr1': 	{'code':'#4101', 'message':'Escriba un nombre nuevo para la playlist'},
			'renameErr2': 	{'code':'#4102', 'message':'Has vuelto a poner el mismo nombre a la playlist'},
			'renameErr3': 	{'code':'#4103', 'message':'Ya existe una playlist con ese mismo nombre'},
			'deleteErr1': 	{'code':'#4201', 'message':'Se ha producido un error al borrar la playlist'},
			'deleteErr2': 	{'code':'#4202', 'message':'No existe la playlist a eliminar'},
			'addSongErr1': 	{'code':'#4301', 'message':'Esta canción ya se encuentra en esta playlist'},
			'addSongErr2': 	{'code':'#4302', 'message':'La canción ya se encuentra en esta playlist'},
			'addSongErr3': 	{'code':'#4303', 'message':'No existe la playlist indicada'},
			'addSongErr4': 	{'code':'#4304', 'message':'No existe esta canción en la playlist %%'},
		},
		'player': { // err #5000 (related to the player and the queue)
			'playlistErr1':	{'code':'#5001','message':'La playlist que se está intentando reproducir no existe.'},
			'playlistErr2':	{'code':'#5002','message':'La playlist en reproducción no contiene la canción seleccionada.'},
		},
	},
},











// ---- English - lang[en] ----
'en': {
	'langName': 'English',
	'startup': {
		'welcome': 'Welcome to mélodie',
		'intro': 'To configure the app you should indicate the paths of where the audio files and disc cover files will be located',
		'audioPlaceholder': 'introduce the audio file path',
		'coverPlaceholder': 'introduce the disc cover path',
		'clearBtn': 'Clear',
		'continueBtn': 'Continue',
		'restoreOptionTxt': 'or<br />Restore a previous mélodie backup',
		'restoreBtn': 'Restore backup',
		'userManual': 'User manual',
	},
	'nav': {
		'home': 'home',
		'mysongs': 'my songs',
		'myplaylists': 'my playlists',
		'noPlaylists': 'No playlists',
		'settings': 'settings',
		'playingIcon': 'playing'
	},
	'homePage': {
		'homeTitle': 'Welcome to %%',
		'homeSubtitle': 'What do you want to hear today?',
		'showAllSongs': 'show all songs',
		'songs': 'Songs',
		'totalPlays': 'Plays',
		'artists': 'Artists',
		'playlists': 'Playlists',
		'notPlayedSongs': 'You haven\'t heard these in a while',
		'notPlayedEver': 'This song has never been played',
		'notPlayedSince': {
			'minutes': ['Since more than %% minute','Since more than %% minutes'],
			'hours': ['Since more than %% hour','Since more than %% hours'],
			'days': ['Since more than %% day','Since more than %% days'],
			'months': ['Since more than %% month','Since more than %% months'],
			'years': ['Since more than %% year','Since more than %% years'],
		},
		'mostPlayedSongs': 'Most played songs',
		'timesPlayed': 'times',
		'showMore': 'show more',
		'warnings': {
			'audioPath': 'WARNING: you have to specify the route where are the audio files',
			'coverPath': 'WARNING: you have to specify the route where are the album cover files',
			'backupNever': 'NOTICE: there\'s no backup stored',
			'backupTwoWeeks': 'NOTICE: the last backup stored is more than two weeks old',
			'backupMonth': 'NOTICE: the last backup stored is more than a month old',
		},
		'firstSteps': {
			'title': 'First steps',
			'songs': ['Add in all your songs','all the songs will be in the My Songs section'],
			'playlists': ['Create playlists','classify the songs how you want'],
			'backup': ['Generate backups','preventing losing data if you delete browser data'],
		},
	},
	'mySongs': {
		'pageTitle': 'Song list',
		'songs': ['song','songs'],
		'minutes': ['minute','minutes'],
		'hours': ['hour','hours'],
		'searchSongs': 'search song',
		'songTitle': 'Title',
		'songArtist': 'Artist',
		'songAlbum': 'Album',
		'songGenre': 'Genre',
		'songDuration': 'Duration',
		'songDateAdded': 'Date added',
		'noSongs': 'There aren\'t songs yet',
	},
	'addSong': {
		'title': 'Add song',
		'subtitle': 'Add song to your song list',
		'titleBanner': 'Type all the new song data',
		'songTitle': {
			'desc': 'Song title',
			'placeholder': 'type here the title',
		},
		'songArtist': {
			'desc': 'Artist name',
			'placeholder': 'type here the name',
		},
		'songAlbum': {
			'desc': 'Album name',
			'placeholder': 'type here the name',
		},
		'songGenre': {
			'desc': 'Musical genre',
			'placeholder': 'type here the genre',
		},
		'songPublished': {
			'desc': 'Launch date',
			'placeholder': 'type here the year',
		},
		'songCover': {
			'desc': 'Album cover',
			'placeholder': 'type the route of the album cover',
		},
		'songAudio': {
			'desc': 'Audio file',
			'placeholder': 'type the route of the audio file',
		},
		'requiredData': 'required field',
		'select': 'Select',
	},
	'editSong': {
		'title': 'Edit song',
		'subtitle': 'Edit the song %% from %%',
		'titleBanner': 'Change the song data',
	},
	'deleteSong': {
		'title': 'Delete song',
		'mainMessage': 'Are you sure you want to delete the song %% permanently.',
		'relatedPlaylistsMsg': 'It\'ll be removed also from the playlists: %%.',
		'noRelatedPlaylistsMsg': 'The song is not included in any playlist.',
		'acceptBtn': 'Delete',
		'discardBtn': 'Cancel',
	},
	'newPlaylist': {
		'title': 'New playlist',
		'mainMessage': 'Choose a name for the new playlist',
		'songAdded': 'the song %% will be added to the new playlist',
		'placeholder': 'type here the title',
		'acceptBtn': 'Create',
		'discardBtn': 'Cancel',
	},
	'renamePlaylist': {
		'title': 'Rename playlist',
		'mainMessage': 'Choose a new name for the playlist %%',
		'placeholder': 'type here the new name',
		'acceptBtn': 'Rename',
		'discardBtn': 'Cancel',
	},
	'deletePlaylist': {
		'title': 'Delete playlist',
		'mainMessage': 'Are you sure you want to delete the playlist %% permanently.',
		'acceptBtn': 'Delete',
		'discardBtn': 'Cancel',
	},
	'settings': {
		'title': 'Settings',
		'lastUpdated': 'Last updated on %%',
		'backup': {
			'title': 'Backup',
			'backupText': 'Download a complete backup of all your data stored in the app',
			'backupBtn': 'Download backup',
			'lastBackup': 'last backup: %%',
			'noLastBackup': 'no backup recorded',
			'restoreText': 'Restore data from previous backup. Caution! this process will remove all the current data',
			'restoreBtn': 'Select file',
			'restoreNoSelected': 'no file selected',
			'restoreConfirmBtn': 'Restore',
		},
		'darkMode': {
			'title': 'Dark mode',
			'message': 'Enable the dark mode to avoid damaging your vision',
			'enabled': 'Enabled',
			'disabled': 'Disabled',
		},
		'showPlaylists': {
			'title': 'Show playlists',
			'message': 'Show the list of playlists in the left panel by default',
			'enabled': 'Enabled',
			'disabled': 'Disabled',
		},
		'fileLocations': {
			'title': 'File locations',
			'audioMessage': 'Specify the path in which the audio files will be located. You will have to store in this folder all the songs you will add.',
			'audioPlaceholder': 'type the audio files path',
			'coverMessage': 'Specify the path in which the images of the album cover will be located.',
			'coverPlaceholder': 'type the album cover files path',
			'change': 'Change',
		},
		'avoidedSongs': {
			'title': 'Avoided songs',
			'message': 'You can avoid songs that become repetitive for 15 days. You can continue to play them by clicking on them, but they will not appear in the queue until the time expires.<br /><br />Current avoided songs:',
			'songTitle': 'Title',
			'artist': 'Artist',
			'endDate': 'Expire Date',
			'unavoid': 'Unavoid',
			'unavoidBtn': 'Stop avoiding this song',
			'noSongsAvoided': 'There are no avoided songs',
		},
		'language': {
			'title': 'Page language',
			'message': 'All the texts in this page will be displayed in the language selected',
		},
		'availableStorage': {
			'title': 'Available Storage',
			'message': 'Detail about the storage available, necessary for the app to work',
			'appUsage': 'Use of %%: %%',
			'localstorageUsage': 'Use of localstorage: %%',
		}
	},
	'context': {
		'editSong': 'edit',
		'deleteSong': 'delete',
		'avoidSong': 'avoid song',
		'unavoidSong': 'unavoid song',
		'addToPlaylist': 'add to playlist ->',
		'addToNewPlaylist': 'new playlist',
		'removeSongFromPlaylist': 'remove',
		'newPlaylist': 'new playlist',
		'renamePlaylist': 'rename',
		'deletePlaylist': 'delete',
	},
	'errors': {
		'general': { // err #1000 (critical app errors)
			'changeLangErr1': {'code':'#1101','message':'The language selected is not available.'},
			'playSongErr1': {'code':'#1201','message':'The song could not be played'},
			'startupErr1': {'code':'#1301','message':'you should indicate the audio files path'},
			'startupErr2': {'code':'#1302','message':'you should indicate the disc cover file path'},
			'startupErr3': {'code':'#1303','message':'indicate the paths where the audio files and disc cover files are located'},
		},
		'data': { // err #2000 (importdata, integrity of the data)
			'importErr1': {'code':'#2001','message':'The file doesn\'t have an allowed format.'},
			'importErr2': {'code':'#2002','message':'The file doesn\'t have an allowed format.'},
			'importErr3': {'code':'#2003','message':'The file doesn\'t have an allowed format.'},
			'importErr4': {'code':'#2004','message':'The imported data comes from a previous version of the app. Errors may occur.'},
		},
		'songs': { // err #3000 (related to songs)
			'addErr1': 		{'code':'#3001','message':'Required data fields remain to be filled in.'},
			'addErr2': 		{'code':'#3002','message':'The image o audio forma format is not supported.'},
			'addErr3': 		{'code':'#3003','message':'This audio file was already used in another song added.'},
			'addErr4': 		{'code':'#3004','message':'An error occurred reading the audio file indicated.'},
			'addErr5': 		{'code':'#3005','message':'The audio introduced is not playable.'},
			'editErr1': 	{'code':'#3101','message':'Required data fields remain.'},
			'deleteErr1': 	{'code':'#3201','message':'An error occurred deleting the song.'},
		},
		'playlists': { // err #4000 (related to playlists)
			'addErr1': 		{'code':'#4001', 'message':'Introduce a name for the playlist.'},
			'renameErr1': 	{'code':'#4101', 'message':'Introduce a new name for the playlist.'},
			'renameErr2': 	{'code':'#4102', 'message':'You have entered again the same name for the playlist.'},
			'renameErr3': 	{'code':'#4103', 'message':'Already exists a playlist with this name.'},
			'deleteErr1': 	{'code':'#4201', 'message':'An error occurred deleting the playlist.'},
			'deleteErr2': 	{'code':'#4202', 'message':'The playlist to be deleted doesn\'t exist.'},
			'addSongErr1': 	{'code':'#4301', 'message':'This song is already in this playlist.'},
			'addSongErr2': 	{'code':'#4302', 'message':'The song is already in this playlist.'},
			'addSongErr3': 	{'code':'#4303', 'message':'The indicated playlist doesn\'t exist.'},
			'addSongErr4': 	{'code':'#4304', 'message':'This songs does not exist in the playlist %%'},
		},
		'player': { // err #5000 (related to the player and the queue)
			'playlistErr1':	{'code':'#5001','message':'The playlist you are playing doesn\'t exist.'},
			'playlistErr2':	{'code':'#5002','message':'The playlist played does not contain the song selected.'},
		},
	}
}

}